### ISSUE TITLE
Docs are available on readthedocs.io

### ISSUE THREAD

**Issue by ru37z** [fkie-cad/Logprep#1]
Compiling the docs can be inconvenient, so it would be nice to have an up-to-date version on readthedocs.io, as many other open-source tools do.

Definition of Done:
* Logprep docs are available on readthedocs.io
* The docs are automatically updated when changed
* A link to the docs is added to the readme file under "Documentation"

**Comment by ppcad** [comment]
The documentation is now available at https://logprep.readthedocs.io/en/latest/, the necessary webhooks for automatic updates have been created and it is referenced in the readme.
