### ISSUE TITLE
Split kafka connector into input and output connectors

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#141]
**Is your feature request related to a problem? Please describe.**
Currently the confluentkafka connector is a joint connector with an input and an output.
This should be split into an input and and output connector so that those can be more easily combined with other connectors.

**Describe the solution you'd like**
An input and output connector should exist for kafka.
However, it should be possible to use confluentkafka with the same configuration as before.

**Comment by ekneg54** [comment]
I think it makes no sense to split the connectors and then merge them together again to avoid changing the configuration. Yes it would be a breaking change, but we had a lot of them in the last weeks.

I think the better solution would be to split the connector in input and output and merge them via configuration in the pipeline.yaml:

```yaml
connectors:
  input:
    type: kafka
   ...
  output:
    type: elasticsearch
   ... 

```

This would reduce overhead to produce already merged processors via code and should be more flexible.

**Comment by ppcad** [comment]
I see what you mean, but this is not unique to the kafka connector. It is how logprep works for all connectors. An input and an output are being returned by specifying the name of a connector. This what the connector factory has done for the kafka connector in the background before as well.
Furthermore. the connector factory does a bit more than just return input and output in this case. It also connects the two together in a specific way.
What you suggest is changing how connectors work in general and it might be worth doing, but it is beyond the scope of this issue.

**Comment by ekneg54** [comment]
We will have a lot more connectors in future. I think it is worth to go 3 steps back and revalidate the architecture how connectors are implemented now.

If we have no clean borders and responsibilities of what is done by what and how the main things are connected, we will produce work which isn't necessary. And beyond this the system will become unmaintenable quickly. 

Let's take these steps back and do it right now cause we have the chance to make things easier for future work.
