### ISSUE TITLE
Add processor that performs adaptive misuse detection on command-line events

### ISSUE THREAD

**Issue by clumsy9** [fkie-cad/Logprep#177]
**Is your feature request related to a problem? Please describe.**
Currently, the logprep pre-detector enables to perform misuse detection of incoming command-line events. Commonly known command-line obfuscation techniques enable to evade many command-line signatures. 

**Describe the solution you'd like**
An additional processor should perform adaptive misuse detection on process creation events to also detect malicious command-lines that are .e.g. obfuscated. In case of a positive result, additional rule attribution shall be performed.

**Comment by ekneg54** [comment]
could you provide an example log message and the expected result?
