### ISSUE TITLE
Status_Logger crashes pipeline after status_logger period

### ISSUE THREAD

**Issue by urdit52** [fkie-cad/Logprep#2]
When deploying the Quickstart environment provided in the main branch of this repository, one of the pipelines crashes after 30 minutes.

## Expected Behavior

The pipeline should not crash on a regular basis.

## Current Behavior

When starting Logprep using the provided Quickstart environment, whenever the rotating log file for the status_logger is written (every 30 minutes by default), one pipeline crashes.   
  
<img width="1108" alt="Screenshot 2021-08-17 at 16 37 57" src="https://user-images.githubusercontent.com/89061921/129748770-02b134bf-3c79-45d0-b7e4-884a8f8cac89.png">

## Possible Solution

The culprit is util/processor_stats.py and the issue seems to stem from the following static methods expecting `self` as an additional parameter, as the class StatusTracker is instanciated:

`_get_sorted_output_dict`
`_add_derivative_data`
`_add_relevant_values_to_multiprocessing_pipelines`
`_aggregate_error_type`
`_remove_numpy_arrays`

## Steps to Reproduce

1. Start Quickstart environment via `docker-compose --profile logprep up -d` (see README.md)
2. Wait for 30 minutes.
3. Look at Logprep's console output via the Docker CLI (Logprep container) and observe the stack trace.

## Context (Environment)

Python 3.6 (including Logprep requirements), as deployed within the Quickstart docker environment.

## Possible Implementation

Removing the @staticmethod decorator and adding `self` as the first parameter to the above methods' definitions seems to solve the problem here.

**Comment by ppcad** [comment]
Thank you for reporting. This bug is fixed with pull request #4.
