### ISSUE TITLE
DeleterRule throws UnboundLocalError

### ISSUE THREAD

**Issue by DFromPMC** [fkie-cad/Logprep#246]
I found a possible bug in the Deleter processor of logprep version 4.0.0.

Using `deleter.delete` doesnt work and throws an "UnboundLocalError":

`File "/logprep-env/lib/python3.8/site-packages/logprep/processor/deleter/rule.py", line 36, in normalize_rule_dict
    if deleter_config is not None:
UnboundLocalError: local variable 'deleter_config' referenced before assignment`

The rule config for this error looks as followed:
`{
        "filter": "message",
        "deleter": {
            "delete": true
            }
        }`

But the Deleter processor works fine using the deprecated feature `delete` and is deleting the message succesfully. The rule config for 
this looks as followed:
`{
        "filter": "message",
        "delete": true
        }`

Please comment if you need further information for this Bug. Thank you :)

**Comment by ekneg54** [comment]
you are right. Will be fixed in next release.
