### ISSUE TITLE
Provide Issue Templates

### ISSUE THREAD

**Issue by urdit52** [fkie-cad/Logprep#3]
Providing structured templates for submitting issues helps us to deal with issues more efficiently. 

For the creator(s) of future tickets, these are useful by pre-structuring the necessary level of information that is to be included when submitting an issue.

Possible sources of inspiration are:
[awesome-github-templates](https://github.com/devspace/awesome-github-templates)
[github-issue-templates](https://github.com/stevemao/github-issue-templates/)

**Comment by ppcad** [comment]
Thank you for bringing this to our attention.
Templates have been added in #7.
