### ISSUE TITLE
Replace python-hyperscan by pyperscan

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#310]
Python-hyperscan only support amd64 based systems. So it can not be used on OSX. Furthermore the future of this project is questionable because the maintainer is searching for support. We should try to investigate to replace it by https://github.com/vlaci/pyperscan

It is a wrapper for hyperscan and vectorscan written in Rust and I think we should give it a try.

**Comment by ppcad** [comment]
Hyperscan had two new releases in August.
It seems to support Python 3.12 and OSX starting with version 0.5.0: https://pypi.org/project/hyperscan/0.5.0/

However, the maintainer does still search for support.

**Comment by ekneg54** [comment]
We do not follow this path further more because pyperscan is not feature complete.
