### ISSUE TITLE
normalize rule change naming to normalizer

### ISSUE THREAD

**Issue by sascharau** [fkie-cad/Logprep#316]
Rules are passed up to the normalizer with the processor key. Could you implement this behaviour on the normalizer as well? The rule must currently be passed with normalize, the "r" is missing.

**Comment by ekneg54** [comment]
we didn`t do it because we want to deprecate the normalize in favor of 3 other processors. because the normalizer concentrates to much work on it. if it blocks you hard, we should consider to implement this in the normalizer as well or speed up development for the alternatives of the normalizer

**Comment by sascharau** [comment]
We currently have a workaround. However, it is also a dependency we would like to avoid in the future. I just wanted to get it off my chest. The ticket can be closed, Thx!
