### ISSUE TITLE
Dissector: Support type conversion within dissect pattern

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#327]
Filebeat's implementation of the dissect processor allows a direct data type conversion within the dissect string, e.g.:

`%{service.pid|integer} - %{service.name}"` (see [ElasticDocumentation](https://www.elastic.co/guide/en/beats/filebeat/current/dissect.html))

A similar implementation for the dissector would make it easier to auto-generate the mapping including all type conversions.

**Comment by ekneg54** [comment]
Thank you for your feature request. It should be very simple to achieve this.
