### ISSUE TITLE
Logprep doesn't work with legacy SSL certificates

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#356]
confluent-kafka 2.0.2 uses OpenSSL 3.0.x, which is incompatible with some older certificates.
Thus no connections to Kafka are possible if using such certificates.
It should be possible to configure Logprep to allow legacy certificates.

**Steps to reproduce**
Run Logprep with a kafka connector using SSL.

Logprep wil log warnings that it can not verify the SSL certificate and it will notread/write any events.

**Environment**

Logprep version: c549a3c946d11762f25ac6f9bfbb01665efe2b77
Python version: 3.9

**Comment by ekneg54** [comment]
as suggested here: https://github.com/confluentinc/confluent-kafka-python/issues/1521 the best way to solve this is to update the certificates to use stronger ciphers as weak ciphers are disabled by default. 

as a workaround we could make the librdkafka option `ssl.provider` configurable. But if we do this, it could be a better solution to decouple the kafka configuration completely to give all configuration options in users hands.

**Comment by ekneg54** [comment]
I added the possibility to give all kafka config options in #357 
With this you have the chance to find a configuration that fits to your usecase without code changes.

**Comment by ppcad** [comment]
Thank you! I will test this out as soon as possible.
