### ISSUE TITLE
Dissector - Set config parameter target_field to init=False

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#372]
For Dissector rules, it is not sensible to set the parameter target_field, since the name of the resulting field(s) is defined by the dissect pattern (mapping). Therefore, init should be set to False (as done e.g. in the SelectiveExtractor).

Please also review if other dissector parameters should be init=False as well.

**Comment by ekneg54** [comment]
thanks for your issue. we will address this as soon as possible by revising the config parameters for all processors and flag them with `attrs` option `init=False` if they are not needed
