### ISSUE TITLE
Source field does not work in Grokker and Dissector.

### ISSUE THREAD

**Issue by sascharau** [fkie-cad/Logprep#383]
When you pass source_fields to the rule configurations, you get: Logprep grokker TypeError: GrokkerRule.Config.__init__() got an unexpected keyword argument 'source_fields'

config:
```
generic_rules = [
  {
    "filter": "message",
    "description": "",
    "grokker": {
      "source_fields": [
        "message"
      ],
      "mapping": {
        "message": "is grokker working (?<question>[A-Za-z0-9]+)"
      }
    }
  }
]
```

It would be great if you could help me

**Comment by ekneg54** [comment]
Source_fields is not needed. Grokker is the same interface as the dissector. You only need the mapping

**Comment by sascharau** [comment]
The behavior has changed from 6.0 to 6.1 (dissector). No matter what value I enter, I get the error. If source_fields is not needed, could the field be removed in Logprep Rule.Config?

**Comment by ekneg54** [comment]
Yes sure... The source_fields field was never needed in prior releases. But it did not matter if it was filled. This changed because it does not make sense to fill this field, because it is overwritten by the rule with the fields used in mapping

**Comment by ekneg54** [comment]
https://github.com/fkie-cad/Logprep/blob/main/logprep/processor/dissector/rule.py#L167

Here source_fields is filled for grokker and dissector

**Comment by ekneg54** [comment]
Could we close this?

**Comment by niklas-kunz** [comment]
I think we can close this issue, yes. Since init=False, it is clear that source fields is not a required parameter for configuration (see [dissector/rule.py](https://github.com/fkie-cad/Logprep/blob/main/logprep/processor/dissector/rule.py), line 145).
