### ISSUE TITLE
all processors should support specific and generic rules

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#41]
**Is your feature request related to a problem? Please describe.**
* not all processors use generic and specific rules
* processors do not implement a common interface

**Describe the solution you'd like**
* all processors should implement a common interface
* all processors should implement the possibility to configure generic and specific rules
* all processors should implement a rule tree

**Describe alternatives you've considered**
* none

**Additional context**
* it is hard to implement further behavour to all processors because they do not share a common interface.

**Comment by trimborn** [comment]
This looks like a good idea, except the last point of your solution. As far as i remember are there are processors like the clusterer who could not profit of the implementation of a rule tree, as they work in a complete different way.

**Comment by ekneg54** [comment]
> This looks like a good idea, except the last point of your solution. As far as i remember are there are processors like the clusterer who could not profit of the implementation of a rule tree, as they work in a complete different way.

I refactored it here and it seems to not interfere: #39 

the aim is not to improve the behaviour. the main aim is to ensure a generalized interface implemented by all processors.
