### ISSUE TITLE
Grokker failure for PATH pattern

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#413]
Some patterns can be applied successfully, like in this example:

```
// Input field: 
"info": {
    "time": "10:12:31"
}
```

```
// Grokker configuration (mapping):
{
  "info.time": [
    "%{TIME:time}"
  ]
}
```

For the PATH pattern, however, the Grokker returns a Grokker Failure:

```
// Input field:
"log": {
    "file": {
        "path": "/usr/http/http-client.log"
    }
}

```
```
// Grokker configuration (mapping):
{
    "log.file.path": [
        "%{PATH:path_grok}"
    ]
}
```

This returns the following warning:
`ProcessingWarning in Grokker (grokker): no grok pattern matched. 
`

The mapping was tested successfully on https://grokdebugger.com/

**Comment by dtrai2** [comment]
Apparently the Grok pattern `PATH` is a combination of `UNIXPATH` and `WINPATH` and the former wasn't supported in python. I did open a pull request to fix it. In the meantime it should work for you if you use instead the `URIPATH` pattern.

**Comment by niklas-kunz** [comment]
Thank you for addressing this issue. In the meantime, I was able to use the `URIPATH` pattern successfully.
