### ISSUE TITLE
Printed events processed interval does not correspond to real processing time

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#429]
Logprep can print the number of processed events for a configured interval.
However, the printed interval is smaller than the actual processing time if processing one event takes longer than that interval.
This can happen when Logprep is starting if it has to load a lot of rules and the print interval is smaller than the time it takes to load them.

**Expected behavior**
The printed interval for processed events corresponds to the real processing time.

**Current behavior**
The printed interval for processed can be smaller the real processing time.

**Steps to reproduce**
Set a small "print_processed_period" and load a lot of rules.

**Environment**

Logprep version: latest
Python version: 3.11

**Possible solution**
This might be solved in multiple ways:

1. Print the real time it took instead of the configured interval time. This means the printed interval might increase if it took longer than configured.
2. Ensure the processed count gets always printed at the interval, even if events are still being processed.
3. Ensure everything is loaded before the counting starts.

**Comment by dtrai2** [comment]
I just opened a pull request, maybe you can check if that solves the issue.
