### ISSUE TITLE
DomainResolver deletes logs in some cases

### ISSUE THREAD

**Issue by Malutthias** [fkie-cad/Logprep#433]
Some logs are deleted in the logprep while processing in domain_resolver preprocessor.

ProcessingCriticalError in **DomainResolver** (domain_resolver): encoding with 'idna' codec failed (UnicodeError: l_abel empty or too long_) -> event was **deleted**

**Expected behavior**

Writing to an error index with descriptive error message.

**Current behavior**

Deletion of relevant logs

**Steps to reproduce**

Running logprep and process examples with either an empty label or too long a lable for the domain_resolver.

**Environment**

Logprep version: latest
Python versions: 3.11
Environment: Kubernetes with containerd

**Comment by dtrai2** [comment]
Can you please double check if you are using the latest version? We made a release last thursday and the MR #428 should have fixed this already.

**Comment by Malutthias** [comment]
Ok, admin says we're on 23.07.03 in our test system were it happened. We'll check

**Comment by Malutthias** [comment]
Works as intended.
