### ISSUE TITLE
Deleter doesn't delete logs

### ISSUE THREAD

**Issue by Malutthias** [fkie-cad/Logprep#434]
When using the deleter, nothing is deleted and an empty file is dragged through the whole pipeline resulting in only containing the processing times in the meta-data.

**Expected behavior**

Immediately deletes the log when filter of deleter matches in preprocessor step.

**Current behavior**

Creates an empty dictionary thats entirely processed and at the end, cause of a non existing index gets written into default instead.

**Steps to reproduce**

1. Running Logprep
2. Enabling the preprocessor **deleter**
3. Look at default index

**Environment**

Logprep version: 23.07.03
Python version: 3.11
Enviroment: Kubernetes with containerd

**Comment by ppcad** [comment]
The issue still persists after #437.
`if caller.name == "deleter" and not event:` references the name of the processor and not the type.
This can be different from `deleter`.
Furthermore, other callers (like MultiprocessingPipeline) can still apply the times, even if the caller name was matching.

@dtrai2
Could you please have another look?

**Comment by ekneg54** [comment]
Or caller.type?

**Comment by dtrai2** [comment]
I just opened a second pull request. @ppcad could you please check it out?
I did go for the option `caller.__class__.__name__` as the `Deleter` class doesn't have a `type` attribute, such that `caller.type` wouldn't work. Another option would be `caller._config.type`, but I did not chose that as not every class that has this `measure_time` annotation might have a `_config` object.
