### ISSUE TITLE
[Feature Request] Support for IPinfo IP to Country ASN database

### ISSUE THREAD

**Issue by abdullahdevrel** [fkie-cad/Logprep#443]
Requesting integrating IPinfo's [free IP to Country ASN database](https://ipinfo.io/products/free-ip-database). Features of the database:

- Full accuracy with daily updates.
- Includes IPv4 and IPv6 addresses in a single db
- Comes in MMDB format and is functional with existing MMDB reader library
- Released under a commercially permissible CC-BY-SA 4.0 license

Database schema: https://ipinfo.io/developers/ip-to-country-asn-database

Although the database does not provide city-level data, it is not a reduced-accuracy version database but rather a limited yet fully accurate IP Geolocation database. The database provides granular data records for each IP address and does not aggregate ranges.

Looking at the current implementation of the IP geolocation enrichment feature, it looks specific field look-ups is somewhat complex due to the IP database's nested data structure. I could be missing some context though.

In [`_try_getting_geoip_data`](https://github.com/fkie-cad/Logprep/blob/main/logprep/processor/geoip_enricher/processor.py#L86) function, I believe you are using a block-level try-catch statement for missing values.

```
    def _try_getting_geoip_data(self, ip_string):
        try:
# ...

            geoip_data |= {
                "properties.accuracy_radius": ip_data.location.accuracy_radius,
                "properties.continent": ip_data.continent.name,
                "properties.continent_code": ip_data.continent.code,
                "properties.country": ip_data.country.name,
                "properties.country_iso_code": ip_data.country.iso_code,
                "properties.time_zone": ip_data.location.time_zone,
                "properties.city": ip_data.city.name,
                "properties.postal_code": ip_data.postal.code,
                "properties.subdivision": ip_data.subdivisions.most_specific.name,
            }

# ...
        except (ValueError, AddressNotFoundError):
            return {}
```

However, I have consistently found that `city`, `postal_code` fields missing from the from the IP database that you are using. So when you do block level `try-catch` statement, I believe that you might be ignoring IP metadata that is present. Also, the `most_specific` method is related to the `subdivisions` element being a list element.

On the other hand, IPinfo provides data in a tabular format. In cases where there are missing data, IPinfo keeps the field and returns an empty string. This is valuable for reducing code complexities.

```python
{'as_domain': 'ptcl.com.pk',
 'as_name': 'Pakistan Telecommunication Company Limited',
 'asn': 'AS17557',
 'continent': 'AS',
 'continent_name': 'Asia',
 'country': 'PK',
 'country_name': 'Pakistan'}
```

I have written a small article after reviewing the project: https://community.ipinfo.io/t/the-problem-with-nested-and-irregular-data-structures-in-ip-databases/2846

On the other hand, I have also found ASN information to be quite valuable in log enrichment. In threat intelligence operations a combination of ASN and country-level information provides a very robust set of information.

If you have any questions or feedback, please let me know. I usually do my log enrichment through static log dumps, so I was not able to test out the project. So, apologies in advance if I am missing any crucial information.

**Comment by ekneg54** [comment]
hello @abdullahdevrel ,

thank you for your feature request, but currently we do not plan to change the implementation of our geoip features.

**Comment by abdullahdevrel** [comment]
@ekneg54 I really appreciate you taking a look at the request. If you reconsider the request in the future, I will be happy to help. 

Have an awesome week.
