### ISSUE TITLE
`JsonlOutput` keeps processed events in memory?

### ISSUE THREAD

**Issue by clumsy9** [fkie-cad/Logprep#468]
I am not sure if this is actually a bug or more of a feature request regarding one of the output connectors.

I am planning to use the `JsonlOutput`-Connector to perform some test-runs using dedicated datasets. While browsing the connector's code, I recognized that `JsonlOutput` keeps events that are written to file in additional list attributes `events` and `failed_events`.  If I am not mistaken, events inserted into these lists are never removed, which leads to an increasing memory usage. Depending on the dataset, this could be somewhat problematic at some point.

As there are also unit tests  for both event lists, I thought to myself that there must be (or have been) specific use cases for the `JsonlOutput`-Connector where keeping all events in memory is actually required. Is this still the case? Or can both lists be considered as artifacts from earlier development stages, and are actually not required anymore?

**Comment by ekneg54** [comment]
This connector is only used by us for testing. It is not designed to be a valid production ready output connector.

If you need this feature feel free to send a PR.

**Comment by clumsy9** [comment]
We implemented this feature for local testing, but it is not used or required anymore. Therefore, I will close this issue.
