### ISSUE TITLE
Rewrite auto_rule_tester.py 

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#517]
the auto_rule_tester module is very verbose, error prone and could be rewritten with focus of readability and reusing in logprep already present methods for standard things.

 
https://github.com/fkie-cad/Logprep/blob/main/logprep/util/auto_rule_tester/auto_rule_tester.py

**Comment by ekneg54** [comment]
currently the auto-rule-tester is broken in 10.0.2, because the mechanic to get the tests from the filename of a rule does not work anymore. 

I think it is time to brainstorm a new solution for this to get to work without changing too much in the current Configuration Object.

one way could be to write the tests in the rule files as part of the rule, so it is loaded with the rule.
another way could be to rewrite the autorule tester to work with multiple configs.

**Comment by ekneg54** [comment]
another valid path could be to delete the auto rule tester in favor of the auto-rule-corpus tester

**Comment by ppcad** [comment]
I made a hotfix for the auto rule tester, by changing how it's called from run_logprep.py.
It does support only one config per call.

**Comment by ppcad** [comment]
I made it accept multiple configuration files to fix the unit tests.
