### ISSUE TITLE
Addition of caching functionality to the GenericAdder

### ISSUE THREAD

**Issue by Malutthias** [fkie-cad/Logprep#534]
We advocate for the integration of a caching feature into the GenericAdder to address a crucial requirement. This need arises due to the preprocessor's frequent database checks for updates. Presently, these connections are sequentially established within each Logprep instance.

The rationale behind this proposal stems from the potential expansion of fields within such rules. Without caching, this growth could overwhelm the database. Furthermore, retaining open connections to the database might seem viable, but it would lead to a substantial surge in the number of connections, potentially up to 10-15 times per field.

**Comment by ekneg54** [comment]
I suggest to hide your database behind an API and drop the MySQL Feature from the generic adder. Instead you could use the config refresh mechanic in combination with a list from URL as supportet for all lists
