### ISSUE TITLE
Usage of Regex-Filter with Regex-Fields and Multiline Option is not working

### ISSUE THREAD

**Issue by Ohmsnipe** [fkie-cad/Logprep#545]
Using Regex Multiline Filters in combination with the generic adder are not working.

**Expected behavior**

Message: This is a long Test message and it has more lines than usual .

`
filter: 'Message: "(?m).*Test.*"' \n
regex_fields: Message
generic_adder:
  extend_target_list: True
  add:
    Key: "Value"
description: "My description"
`

**Current behavior**

No hit of the Regex and no filling of value in key

**Steps to reproduce**

Hit of the Regex and Filling the key with value in the generic adder

**Environment**

Logprep version:
Python version:
10

**Possible solution**
Fix Multiline Bug

**Possible implementation**

**Comment by ekneg54** [comment]
thank you for your bug report. As for now the filter language of logprep does not allow multiline regex. We plan to implement a kind of fuzzy filter logic to address this. 

Like this: https://www.elastic.co/guide/en/elasticsearch/reference/8.12/query-dsl-query-string-query.html#query-string-fuzziness
