### ISSUE TITLE
TimestampDiffer - parameter "diff" missing in rule documentation

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#632]
**Expected behavior**
The rule documentation of the TimestampDiffer processor should include a description of all parameters.

**Current behavior**
The parameter `diff` is not described in the [current documentation](https://logprep.readthedocs.io/en/latest/user_manual/configuration/processor.html#timestampdiffer). 

**Possible solution**
Adapt docstring of the `classlogprep.processor.timestamper.rule.TimestamperRule.Config` in order to fix the documentation. It would also be helpful to know the syntax expected in the `diff` field.

**Comment by ekneg54** [comment]
thank you for the feedback
