### ISSUE TITLE
Error when depseudonymizing field using CLI

### ISSUE THREAD

**Issue by niklas-kunz** [fkie-cad/Logprep#638]
I want to pseudonymize a field using the Pseudonymizer. Afterwards, to validate that the pseudonym was generated correctly, I want to depseudonymize the field using the Logprep CLI.

**Expected behavior**
After pseudonymizing a field, I want to be able to transform the pseudonym back to the original field value using the appropriate keys.

**Current behavior**
As opposed to the CLI command `logprep pseudo`, which works as expected, I am not able to use a pipeline to generate a pseudonym which I can then depseudonymize to validate that pseudonymization was performed correctly.

**Steps to reproduce**

My exemplary event:
```
{
    "user":"admin"
}
```

My exemplary pipeline:
```
version: logprep-demo-0.0
pipeline:
- pseudonymizer:
    type: pseudonymizer
    specific_rules: []
    generic_rules:
        - filter: user
          pseudonymizer:
            id: random-id
            mapping:
              user: RE_WHOLE_FIELD
    outputs:
        - my_jsonl_output: pseudonyms
    pubkey_analyst: analyst.crt
    pubkey_depseudo: depseudo.crt
    hash_salt: secret_salt
    regex_mapping: regex_mapping.json
    max_cached_pseudonyms: 1000000
    mode: GCM
input:
  myjsoninput:
    type: json_input
    documents_path: event.json
    repeat_documents: false
output:
  my_jsonl_output:
    type: jsonl_output
    output_file: output.jsonl
    output_file_custom: ""
    output_file_error: ""
```

My regex mapping file:
```
{
  "RE_WHOLE_FIELD": "(.*)"
}
```

Output after running Logprep:
``` 
{"user": "<pseudonym:70bda0129bd0bc981da61ad88b26429cfb447b1b8948fcb7aab40b7602788509>"}
``` 

Error when trying to depseudonymize field using CLI command:
- Command used:    
`logprep pseudo depseudonymize analyst.key depseudo.key 70bda0129bd0bc981da61ad88b26429cfb447b1b8948fcb7aab40b7602788509`

- Error thrown: 
```
Traceback (most recent call last):
  File "/usr/local/bin/logprep", line 8, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.10/dist-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/logprep/util/pseudo/commands/depseudonymize.py", line 29, in depseudonymize
    else DualPKCS1HybridCTRDecrypter(pseudo_string)
  File "<string>", line 6, in __init__
  File "/usr/local/lib/python3.10/dist-packages/logprep/util/pseudo/decrypter.py", line 143, in __post_init__
    self.pseudonym = CTRPseudonym(
TypeError: CTRPseudonym.__init__() missing 2 required positional arguments: 'cipher_nonce' and 'ciphertext'
```

##### Notes
- I generated the keys using the CLI as explained in the [user manual (chapter "pseudonymization tools")](https://logprep.readthedocs.io/en/latest/user_manual/execution.html#generate-keys). As explained in the manual, I am using the public keys (`.crt`) for pseudonymization and the private keys (`.key`) for depseudonymization. 
- As hash salt, I am using the string `secret_salt`.

**Environment**

Logprep version: 13.0.1 
Python version: 3.10.12

**Final Remark**
Please let me know if there is any mistake in my configuration or if there is something else that I should try (e.g. use other set of keys).

**Comment by ekneg54** [comment]
This is not the Pseudonym. This is the key for the Pseudonym. The real pseudonym is returned as extra_data from the processor and afterwards stored in the defined output.

**Comment by niklas-kunz** [comment]
@ekneg54 Got it. In the case of my [JsonlOutput](https://logprep.readthedocs.io/en/latest/user_manual/configuration/output.html#jsonloutput), where do I see the actual pseudonym then? The output file `output.jsonl` given in my pipeline only includes this:

```
{"user": "<pseudonym:70bda0129bd0bc981da61ad88b26429cfb447b1b8948fcb7aab40b7602788509>"}
{"user": "<pseudonym:70bda0129bd0bc981da61ad88b26429cfb447b1b8948fcb7aab40b7602788509>"}
{"user": "<pseudonym:70bda0129bd0bc981da61ad88b26429cfb447b1b8948fcb7aab40b7602788509>"}
{"user": "<pseudonym:70bda0129bd0bc981da61ad88b26429cfb447b1b8948fcb7aab40b7602788509>"}
```

**Comment by ekneg54** [comment]
You should use the result object returned by the  processors process method or alternativly the pipeline_result returned by logprep.framework.pipeline.Pipeline.process_process_pipeline

**Comment by niklas-kunz** [comment]
Shouldn't it also be included in the output event though? I mean, I would expect to find the pseudonymized user name there

**Comment by ekneg54** [comment]
No. These date schuld be stored separated from the event in another Index or topic

Gesendet von Proton Mail für Android

-------- Ursprüngliche Nachricht --------
Am 23.07.24 13:14 um niklas-kunz schrieb :

**Comment by niklas-kunz** [comment]
Got it! This was the piece of information that I was missing. This issue can be closed then 🙂
