### ISSUE TITLE
opensearch connector raises during processing if ca certificate not found

### ISSUE THREAD

**Issue by ekneg54** [fkie-cad/Logprep#639]

**Comment by djkhl** [comment]
![image](https://github.com/user-attachments/assets/3d011551-b091-4a6e-8061-0953da85a84e)

**Comment by ekneg54** [comment]
it would be better to include checks during configuration validatation and log an invalidconfiguration error and exit

**Comment by ekneg54** [comment]
On startup the connection to opensearch is checked. So also the certificate is validated. This should not happen an more.
