### ISSUE TITLE
Optimize git workflow with caching

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#84]
**Is your feature request related to a problem? Please describe.**
Some git workflows do not utilize caching, which makes them unnecessarily slow.

**Describe the solution you'd like**
Add caching to workflows where appropriate. Caching could be added to installing dependencies in tests and code quality checks, similarly to how it's done for pex building.

**Describe alternatives you've considered**
Sharing a dependencies across jobs might be an alternative, but it's not clear if this is possible or how complicated it would be.

**Comment by ekneg54** [comment]
We have removed some steps from ci pipeline. Does this issue still persist?

**Comment by ppcad** [comment]
This issue has been solved at some point.
