### ISSUE TITLE
Make relative paths be use configurable base path

### ISSUE THREAD

**Issue by ppcad** [fkie-cad/Logprep#99]
**Is your feature request related to a problem? Please describe.**
Some logprep rules access data via relative paths. Logprep rules can be shared on different systems and relative paths might different for those systems. 
It would be easier change a base path for each processor instead of changing all relative paths for all rules.

**Describe the solution you'd like**
Add an option to give a base path to processors for relative paths in rule files, like it is done for the list comparison processor.

**Describe alternatives you've considered**
The only alternative would be to ensure the same directory structure on all systems or to adapt all path by auto-replace, which is not always a viable solution.

**Comment by ekneg54** [comment]
as seen with #111 we need to add the folder with the configuration file `pipeline.yml` to the python path. 
When this change is added, the rules will be discovered from there too. An extra path should possibly not be needed. 

Would this resolve this issue?

If not, we should solve this in a global manner and not in some special cases per processor

**Comment by ekneg54** [comment]
It is now possible to use environment variables in format `${variablename} ` in all paths used in configuration and rules.

Does this solve this issue?

**Comment by ppcad** [comment]
Yes, thank you for adding that feature.
